version: "3.8"

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      cache_from:
        - my-portfolio:latest
    ports:
      - "3000:3000"
    restart: always
