name: Deploy Portfolio to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} 'bash -lc "
            source ~/.bashrc
            export PATH=$PATH:/home/${{ secrets.VPS_USER }}/.nvm/versions/node/v22.14.0/bin/bun
            export PATH=$PATH:/home/${{ secrets.VPS_USER }}/.nvm/versions/node/v22.14.0/bin/pm2
            export PATH=$PATH:/home/${{ secrets.VPS_USER }}/.nvm/versions/node/v22.14.0/bin/node
            cd /home/${{ secrets.VPS_USER }}/portfolio/
            git pull origin master
            /home/${{ secrets.VPS_USER }}/.nvm/versions/node/v22.14.0/bin/bun install
            /home/${{ secrets.VPS_USER }}/.nvm/versions/node/v22.14.0/bin/pm2 restart portfolio
          "'
